// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yehdbwnzmqjnbkjwezvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaGRid256bXFqbmJrandlenZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzU4MTIsImV4cCI6MjA2Mjc1MTgxMn0.rEdrBEOGDoV51_3wRZn6B-bBvMzhk2gXaVtW2NZQbgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);